name: systray
version: 1
summary: Qt Systray Example
description: Qt Systray Example

apps:
  systray:
    command: qt5-launch systray
    plugs:
      - unity7

parts:
  systray:
    plugin: qmake
    source: src/
    build-packages:
      - qtbase5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
    after: [qt5conf] # A wiki part
